Automatic
Standard
1MyKepler
2MyKepler
3MyKepler
4MyKepler
5MyKepler
Camsat
Research
Russian
Temporary
Weather
;
; Hints:
;
; The files 'SatFiles.SQF', 'WisFiles.SQF' and 'AosFiles.SQF' contain the names of 
; the Satellite Groups that have been installed for the respective main program.
; A maximum of 12 groups for each program are allowed.
; For each entry in the list, a file with the same name has to be present in the 
; SatPC32 directory. Depending on which main program uses the file, its name must 
; contain the extension '.Sat', '.Wis' or '.Aos'. The names of the satellites 
; selected for each group are stored in these files. 
; 'SatFiles.SQF' contains the names of the groups that have been installed for
; SatPC32. If you want to add a group, a file with the same name and with the 
; extension '.Sat' has to be created. To do this, copy the 'Standard.sat'
; file, rename it and then edit it in the Satellites menu.
; Further, the group name has to be added to the list above.
; The new group is available from the next program start.
; To modify the respective Files for Wisat32 ('WisFiles.SQF') and WinAOS
; ('AosFiles.SQF') open these files and edit them as described above.
